pytest coverage

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -150,4 +150,21 @@ jobs:
           pipenv run python manage.py setup_tasks
 
       - name: Run tests with coverage
-        run: pytest --cov=. --cov-report term-missing --cov-fail-under=57
+        run: |
+          for i in 1 2 3; do
+            if pytest --cov=. --cov-report term-missing --cov-fail-under=57; then
+              export PYTEST_COVERAGE_SUCCEEDED=true
+              break
+            else
+              export PYTEST_COVERAGE_SUCCEEDED=false
+            fi
+            sleep 5s
+          done 
+          if [[ "${PYTEST_COVERAGE_SUCCEEDED}" == "true" ]]; then
+            echo "Pytest succeeded"
+          else
+            echo "Pytest failed"
+            exit 1
+          fi
+        env:
+          RETRY_DESCRIPTION: "Running tests with coverage"
